### ISSUE TITLE
Inline `## Not run` regex does not work with older version of v8

### ISSUE THREAD

**Issue by kiendang** [kiendang/rdocsyntax#2]
Originally from https://github.com/kiendang/rdocsyntax/issues/1#issuecomment-816715366 by @eliocamp

This

```js
const inlineNotRunRegex = /(?<=^[^\S\n\r]*##[^\S\n\r]+Not run:)[^\S\n\r]+/gm
```

causes

```
#> "Error with rdocsyntax help server: Error in context_eval(join(src), private$context, serialize): SyntaxError: Invalid regular expression: /(?<=^[^\\S\\n\\r]*##[^\\S\\n\\r]+Not run:)[^\\S\\n\\r]+/: Invalid group\n"
```

with older version of v8

```r
ctx <- V8::v8()
ctx
#> <V8 engine 3.14.5.9> 
#>  $assign(name, value, auto_unbox = TRUE, ...) 
#>  $call(fun, ..., auto_unbox = TRUE) 
#>  $console() 
#>  $eval(src, serialize = FALSE) 
#>  $get(name, ...) 
#>  $reset() 
#>  $source(file) 
#>  $validate(src)
```

**Comment by kiendang** [comment]
@eliocamp I just pushed a workaround. Could you try reinstalling the package from github?

**Comment by eliocamp** [comment]
Works! Thanks!

I don't know if this is intended behaviour, but the "don't run" bits are still commented (not a problem for me)

![image](https://user-images.githubusercontent.com/8617595/114195559-f13c4d00-9926-11eb-8c32-486ae57e9192.png)

**Comment by kiendang** [comment]
Yes the regex was to make the [`Not run`](https://github.com/kiendang/rdocsyntax#inline--not-run) thing highlighted properly, but looks like it was incompatible with some versions of v8 (such as yours) so I disable it temporarily for now until I come up with a regex that works with all v8 versions.

**Comment by kiendang** [comment]
I just pushed a change that re-enables highlighting inline `Not run` for certain v8 versions. It still won't highlight them for your v8 version unfortunately, but at least it doesn't blow up.

You can use a more recent `libv8` with the `V8` R package by running these.

```r
Sys.setenv(DOWNLOAD_STATIC_LIBV8 = 1)
install.packages("V8")
```

Doing that plus reinstalling `rdocsyntax` from github should give you inline `Not run` highlighting.

**Comment by kiendang** [comment]
@eliocamp the current main branch/new release `0.6.0` should fix this issue since we no longer depends on `V8` to run the highlighting code (It's now executed by the browser that eventually displays the doc, *e.g.* RStudio or an external browser).
