### ISSUE TITLE
Stops working after reboot

### ISSUE THREAD

**Issue by arthur-albuquerque** [kiendang/rdocsyntax#5]
Hi, this is a great package. Do I have to run "rdocsyntax::highlight_html_docs()" everytime I open RStudio?

Is there a way I could just run it a single time and it permanently changes the colors?

**Comment by kiendang** [comment]
Yes just put `rdocsyntax::highlight_html_docs()` in your `.Rprofile`

**Comment by kiendang** [comment]
I'm just gonna close this. If you still have issues with this, feel free to reopen.
